[package]
name = "chili-parser"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
chumsky = { workspace = true }
ariadne = { workspace = true }
indexmap = "2.13.0"
